version: "3.7"

services:
  vscode:
    build: .
    volumes:
      - ../:/go-workspace
      - ~/.docker:/root/.docker:z
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:z
      - ~/.zsh_history:/root/.zsh_history:z
      - ~/.gitconfig:/root/.gitconfig:z
      - ~/.kube:/root/.kube:z
    environment:
      - TZ=
    cap_add:
      - SYS_PTRACE
    expose:
      - 8000
    networks:
      - home
    security_opt:
      - seccomp:unconfined
    entrypoint: [ "zsh", "-c", "while sleep 1000; do :; done" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.study-go.rule=Host(`go.study.local`)"
      - "traefik.http.services.study-go.loadbalancer.server.port=8000"
      - "traefik.http.routers.study-go.tls=false"
      - "traefik.http.routers.study-go.service=study-go"
      - "traefik.docker.network=home"

networks:
  home:
    name: home
    external: true
